### PR TITLE
Python port - WIP

### PR DESCRIPTION
**Pull request by EggPool**
Reproduced current state of the JS and tests to Python.

That was easier than thought :)

You can leave it unmerged, and wait until the rest is done to do a single merge, I'm only touching /Python dir.

### CODE REVIEW

**Comment by AngainorDev** [comment]
Looks good, thanks a lot! 
Please ping where you're done!

**Comment by EggPool** [comment]
Temporary state: functional and tested so far with the same tests as JS implementation, but still missing some string types. Do not merge yet.

**Comment by EggPool** [comment]
Seems iso with JS so far, ready for review and merge.

**Comment by AngainorDev** [comment]
Awesome!
Test suite does match, merging.

Thanks a lot!

**Pull request merged**
